### ISSUE TITLE
Uncaught TagError: adsbygoogle.push() error: Ad client is missing from the slot.

### ISSUE THREAD

**Issue by beshoo** [nuxt-modules/google-adsense#194]
Hi,
Why am getting this error?

```
Uncaught TagError: adsbygoogle.push() error: Ad client is missing from the slot.
    at Lp (adsbygoogle.js:215:341)
    at Gp.e.client (adsbygoogle.js:208:43)
    at Le.ea (adsbygoogle.js:54:239)
    at gj (adsbygoogle.js:85:19)
    at Gp (adsbygoogle.js:208:31)
    at Fp (adsbygoogle.js:205:114)
    at adsbygoogle.js:226:346
    at Le.ea (adsbygoogle.js:54:218)
    at gj (adsbygoogle.js:85:19)
    at adsbygoogle.js:224:496
```

**Comment by technoeren13** [comment]
Did you find a solution? @beshoo

**Comment by beshoo** [comment]
> Did you find a solution? @beshoo

No

**Comment by valere-hope** [comment]
Did you find a solution now? @beshoo

**Comment by beshoo** [comment]
> Did you find a solution now? @beshoo

No, i left adsense
